source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

gem "rails", "~> 7.0.3", ">= 7.0.3.1"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "figaro"
gem "bcrypt"
gem "jwt"
gem "blueprinter"
gem "aws-sdk-s3", require: false
gem 'sidekiq'

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

gem "rack-cors"
gem 'rswag'
gem 'rswag-specs'
gem 'rspec-rails'
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'annotate'


  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

